version: '3.9'
services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - name=value
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances: